import * as leadRepository from './lead.repository.js';
import { sendEmail } from '../../utils/sendEmail.js';
import { config } from '../../config/env.js';
import { logger } from '../../utils/logger.js';

export const submitLead = async (leadData) => {
  const newLead = await leadRepository.createLead(leadData);

  // Trigger email alert asynchronously
  if (config.smtp.user && config.smtp.pass && config.smtp.receiverEmail) {
    const htmlTemplate = `
      <div style="font-family: sans-serif; padding: 20px; color: #1e293b; background: #f8fafc;">
        <h2 style="color: #6366f1; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">New Lead Received</h2>
        <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
          <tr style="background: #f1f5f9;"><td style="padding: 10px; font-weight: bold; width: 150px;">Name:</td><td style="padding: 10px;">${newLead.name}</td></tr>
          <tr><td style="padding: 10px; font-weight: bold;">Email:</td><td style="padding: 10px;">${newLead.email}</td></tr>
          <tr style="background: #f1f5f9;"><td style="padding: 10px; font-weight: bold;">Phone:</td><td style="padding: 10px;">${newLead.phone || 'N/A'}</td></tr>
          <tr><td style="padding: 10px; font-weight: bold;">Service Code:</td><td style="padding: 10px; text-transform: uppercase;">${newLead.service}</td></tr>
          <tr style="background: #f1f5f9;"><td style="padding: 10px; font-weight: bold;">Message:</td><td style="padding: 10px; white-space: pre-wrap;">${newLead.message}</td></tr>
        </table>
        <div style="font-size: 11px; color: #64748b; margin-top: 30px; border-top: 1px solid #e2e8f0; padding-top: 8px;">
          Alert generated by Kvantum Engine at ${new Date().toLocaleString('en-US', { timeZone: 'Asia/Kolkata' })} IST.
        </div>
      </div>
    `;

    sendEmail({
      to: config.smtp.receiverEmail,
      subject: `[NEW LEAD] ${newLead.name} - ${newLead.service}`,
      html: htmlTemplate,
    }).catch(err => logger.error('[LEAD SERVICE EMAIL ERR]', err));
  }

  return newLead;
};

export const fetchLeads = async () => {
  return await leadRepository.getAllLeads();
};

export const updateLeadDetails = async (id, updateData) => {
  return await leadRepository.updateLeadById(id, updateData);
};
